services:

  mysql:
    image: mysql:8.0
    container_name: gp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_projets_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - devops-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  backend:
    build: ./backend
    image: msboubaker/gp-backend:${TAG:-latest}
    container_name: gp-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gestion_projets_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8089:8080"
    networks:
      - devops-net
    restart: unless-stopped

  frontend:
    build: ./frontend
    image: msboubaker/gp-frontend:${TAG:-latest}
    container_name: gp-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - devops-net
    restart: unless-stopped

networks:
  devops-net:

volumes:
  mysql-data:
